/**
 * Mini App screen copy — spec USR-001: RU and UZ-Latin are MUST, EN SHOULD.
 *
 * Order statuses, fit explanations, AI messages and error codes come from
 * @fashion/core so the bot, the API notifications and this app always say the
 * same thing. Everything here is screen copy only.
 *
 * The UZ strings are Latin script with the proper oʻ/gʻ letters (U+02BB), which
 * is the standard orthography — not an apostrophe, and not Cyrillic.
 */

import { LOCALES, type Locale, translate as translateCore } from '@fashion/core';

type Dict = Record<string, string>;

const ru: Dict = {
  /* Shell */
  'nav.home': 'Главная',
  'nav.search': 'Поиск',
  'nav.stylist': 'Стилист',
  'nav.cart': 'Корзина',
  'nav.profile': 'Профиль',

  /* Generic */
  'common.back': 'Назад',
  'common.close': 'Закрыть',
  'common.cancel': 'Отмена',
  'common.save': 'Сохранить',
  'common.saved': 'Сохранено',
  'common.apply': 'Применить',
  'common.reset': 'Сбросить',
  'common.retry': 'Повторить',
  'common.continue': 'Продолжить',
  'common.done': 'Готово',
  'common.more': 'Ещё',
  'common.less': 'Свернуть',
  'common.all': 'Все',
  'common.from': 'от',
  'common.loading': 'Загружаем…',
  'common.error': 'Что-то пошло не так',
  'common.empty': 'Здесь пока ничего нет',
  'common.search': 'Найти',
  'common.remove': 'Удалить',
  'common.edit': 'Изменить',
  'common.add': 'Добавить',
  'common.yes': 'Да',
  'common.no': 'Нет',
  'common.optional': 'необязательно',
  'common.required': 'обязательно',
  'common.copy': 'Скопировать',
  'common.copied': 'Скопировано',
  'common.share': 'Поделиться',
  'common.days': 'дн.',
  'common.pcs': 'шт.',
  'common.of': 'из',

  /* Home */
  'home.greeting': 'Добрый день',
  'home.greetingMorning': 'Доброе утро',
  'home.greetingEvening': 'Добрый вечер',
  'home.subtitle': 'Бренды Ташкента в одном месте',
  'home.newIn': 'Новое',
  'home.viewAll': 'Смотреть все',
  'home.brands': 'Бренды',
  'home.categories': 'Категории',
  'home.looks': 'Готовые образы',
  'home.sale': 'Скидки',
  'home.askStylist': 'Спросить стилиста',
  'home.stylistPitch': 'Опишите повод — соберём образ из того, что есть в наличии',
  'home.sponsored': 'Реклама',

  /* Search */
  'search.placeholder': 'Бренд, вещь или образ',
  'search.filters': 'Фильтры',
  'search.sort': 'Сортировка',
  'search.results': 'Найдено',
  'search.nothing': 'Ничего не нашлось',
  'search.nothingHint': 'Попробуйте снять часть фильтров или изменить запрос.',
  'search.didYouMean': 'Возможно, вы искали',
  'search.recent': 'Вы искали',
  'search.popular': 'Часто ищут',
  'search.clearFilters': 'Сбросить фильтры',
  'search.filtersApplied': 'фильтр(ов)',
  'sort.relevance': 'По релевантности',
  'sort.newest': 'Сначала новое',
  'sort.price_asc': 'Сначала дешевле',
  'sort.price_desc': 'Сначала дороже',
  'sort.discount': 'Больше скидка',
  'sort.popular': 'Популярное',
  'filter.category': 'Категория',
  'filter.brand': 'Бренд',
  'filter.size': 'Размер',
  'filter.color': 'Цвет',
  'filter.price': 'Цена',
  'filter.material': 'Материал',
  'filter.style': 'Стиль',
  'filter.season': 'Сезон',
  'filter.fitPreference': 'Посадка',
  'filter.occasion': 'Повод',
  'filter.inStockOnly': 'Только в наличии',
  'filter.discountOnly': 'Только со скидкой',
  'filter.priceFrom': 'От',
  'filter.priceTo': 'До',

  /* Product */
  'pdp.selectSize': 'Выберите размер',
  'pdp.size': 'Размер',
  'pdp.sizeChart': 'Размерная сетка',
  'pdp.addToCart': 'В корзину',
  'pdp.addedToCart': 'Добавлено в корзину',
  'pdp.outOfStock': 'Нет в наличии',
  'pdp.notifyMe': 'Сообщить о поступлении',
  'pdp.notifyMeDone': 'Сообщим, когда появится',
  'pdp.lastItems': 'Осталось мало',
  'pdp.onlyLeft': 'Осталось {n}',
  'pdp.composition': 'Состав',
  'pdp.care': 'Уход',
  'pdp.measurements': 'Замеры изделия',
  'pdp.delivery': 'Доставка',
  'pdp.returns': 'Возврат',
  'pdp.returnWindow': 'Возврат в течение {n} дней',
  'pdp.seller': 'Продавец',
  'pdp.soldBy': 'Продаёт',
  'pdp.brand': 'Бренд',
  'pdp.description': 'Описание',
  'pdp.details': 'Характеристики',
  'pdp.countryOfOrigin': 'Страна производства',
  'pdp.authenticity': 'Подлинность',
  'pdp.completeLook': 'С чем носить',
  'pdp.related': 'Похожее',
  'pdp.reviews': 'Отзывы',
  'pdp.noReviews': 'Отзывов пока нет',
  'pdp.verifiedPurchase': 'Покупка подтверждена',
  'pdp.fitVerdict': 'Отзывы о посадке',
  'pdp.yourSize': 'Ваш размер',
  'pdp.whySize': 'Почему этот размер',
  'pdp.improveFit': 'Добавьте мерки — подберём точнее',
  'pdp.fitDisclaimer': 'Это рекомендация, а не гарантия посадки.',
  'pdp.handlingDays': 'Собирают {n} дн.',
  'pdp.chooseSizeFirst': 'Сначала выберите размер',
  'pdp.formality': 'Формальность',
  'pdp.warmth': 'Утепление',

  /* Stylist */
  'ai.title': 'AI-стилист',
  'ai.subtitle': 'Опишите повод, бюджет и настроение',
  'ai.placeholder': 'Например: образ на свадьбу до 3 000 000 сум',
  'ai.generate': 'Собрать образ',
  'ai.generating': 'Собираем образ…',
  'ai.budget': 'Бюджет',
  'ai.budgetAny': 'Без ограничения',
  'ai.total': 'Итого за образ',
  'ai.withinBudget': 'В рамках бюджета',
  'ai.overBudget': 'Выше бюджета',
  'ai.why': 'Почему так',
  'ai.swap': 'Заменить',
  'ai.swapItem': 'Выбрать другое',
  'ai.alternatives': 'Варианты',
  'ai.addAll': 'Добавить весь образ',
  'ai.addedAll': 'Образ в корзине',
  'ai.sellers': 'Продавцов в образе: {n}',
  'ai.history': 'Ваши образы',
  'ai.noHistory': 'Вы ещё не собирали образы',
  'ai.tryAgain': 'Собрать другой',
  'ai.refine': 'Уточнить',
  'ai.examplesTitle': 'Примеры запросов',
  'ai.disclaimer': 'Образ собран из вещей, которые сейчас есть в наличии.',
  'ai.failEmptySlots': 'Для такого образа не хватает вещей в наличии.',
  'ai.failBudget': 'На этот бюджет собрать образ не получится.',
  'ai.failNoCombo': 'Подходящего сочетания не нашлось.',
  'ai.failHint': 'Попробуйте изменить повод, поднять бюджет или снять ограничение по цвету.',
  'ai.nearestBudget': 'Самый доступный похожий образ — {amount}',
  'ai.slotsFound': 'Нашлось вещей по слотам',
  'ai.notPersonalized': 'Включите персонализацию, чтобы учитывать ваш стиль и размеры',

  /* Cart */
  'cart.title': 'Корзина',
  'cart.empty': 'Корзина пуста',
  'cart.emptyHint': 'Добавьте вещи из каталога или соберите образ со стилистом.',
  'cart.goShopping': 'В каталог',
  'cart.subtotal': 'Товары',
  'cart.delivery': 'Доставка',
  'cart.discount': 'Скидка',
  'cart.total': 'Итого',
  'cart.checkout': 'Оформить',
  'cart.itemCount': '{n} товар(ов)',
  'cart.fromSeller': 'От продавца',
  'cart.deliverySeparately': 'Доставляется отдельно',
  'cart.issueOutOfStock': 'Закончился',
  'cart.issuePriceChanged': 'Цена изменилась',
  'cart.issueUnpublished': 'Товар снят с продажи',
  'cart.issueQuantityReduced': 'Доступно меньше',
  'cart.fixIssues': 'Исправьте позиции, чтобы продолжить',
  'cart.removeConfirm': 'Удалить из корзины?',
  'cart.clearConfirm': 'Очистить корзину?',
  'cart.promo': 'Промокод',
  'cart.promoApply': 'Применить',
  'cart.aiPick': 'Из образа',

  /* Checkout */
  'checkout.title': 'Оформление',
  'checkout.address': 'Адрес доставки',
  'checkout.addAddress': 'Добавить адрес',
  'checkout.chooseAddress': 'Выберите адрес',
  'checkout.deliveryMethod': 'Способ доставки',
  'checkout.payment': 'Оплата',
  'checkout.note': 'Комментарий к заказу',
  'checkout.notePlaceholder': 'Например: позвонить перед доставкой',
  'checkout.summary': 'Ваш заказ',
  'checkout.pay': 'Оплатить {amount}',
  'checkout.place': 'Подтвердить заказ',
  'checkout.placing': 'Создаём заказ…',
  'checkout.holdExpires': 'Товар зарезервирован до {time}',
  'checkout.holdExpired': 'Резерв истёк — пересчитаем корзину',
  'checkout.quoteExpired': 'Расчёт устарел. Обновляем.',
  'checkout.sellersNote': 'Заказ разделится на {n} посылк(и) — по одной от каждого продавца',
  'checkout.paymentsNotLive': 'Онлайн-оплата ещё не подключена',
  'checkout.paymentsNotLiveBody':
    'Платёжные провайдеры подключаются отдельно. Сейчас доступна тестовая оплата — деньги не списываются, но заказ проходит весь путь полностью.',
  'checkout.sandboxPay': 'Тестовая оплата',
  'checkout.success': 'Заказ оформлен',
  'checkout.successBody': 'Мы отправим уведомление, когда продавец подтвердит заказ.',
  'checkout.toOrder': 'К заказу',
  'checkout.fiscalNote': 'Чек придёт после оплаты',

  /* Orders */
  'orders.title': 'Заказы',
  'orders.empty': 'Заказов пока нет',
  'orders.active': 'Активные',
  'orders.completed': 'Завершённые',
  'orders.order': 'Заказ',
  'orders.placedAt': 'Оформлен',
  'orders.parcels': 'Посылки',
  'orders.parcel': 'Посылка',
  'orders.tracking': 'Отслеживание',
  'orders.trackingNumber': 'Трек-номер',
  'orders.cancel': 'Отменить заказ',
  'orders.cancelConfirm': 'Отменить заказ целиком?',
  'orders.cancelReason': 'Причина отмены',
  'orders.requestReturn': 'Оформить возврат',
  'orders.receipt': 'Чек',
  'orders.timeline': 'История',
  'orders.total': 'Сумма заказа',
  'orders.refunded': 'Возвращено',
  'orders.paymentPending': 'Ожидает оплаты',
  'orders.payNow': 'Оплатить',
  'orders.rateFit': 'Как сел размер?',
  'orders.fitRunsSmall': 'Маломерит',
  'orders.fitTrue': 'В размер',
  'orders.fitRunsLarge': 'Большемерит',
  'orders.fitThanks': 'Спасибо — учтём в рекомендациях',

  /* Returns */
  'returns.title': 'Возвраты',
  'returns.empty': 'Возвратов нет',
  'returns.create': 'Оформить возврат',
  'returns.chooseItems': 'Что возвращаем',
  'returns.reason': 'Причина',
  'returns.comment': 'Комментарий',
  'returns.refundAmount': 'К возврату',
  'returns.submit': 'Отправить заявку',
  'returns.notEligible': 'Возврат недоступен',
  'returns.windowEnds': 'Возврат возможен до {date}',
  'returns.handover': 'Я передал посылку',
  'returns.cancel': 'Отменить заявку',
  'returns.dropOff': 'Куда передать',
  'returns.created': 'Заявка создана',
  'returns.createdBody': 'Мы напишем, когда продавец примет посылку.',
  'reason.SIZE_TOO_SMALL': 'Размер мал',
  'reason.SIZE_TOO_LARGE': 'Размер велик',
  'reason.NOT_AS_DESCRIBED': 'Не соответствует описанию',
  'reason.QUALITY_ISSUE': 'Качество',
  'reason.WRONG_ITEM': 'Привезли не то',
  'reason.DAMAGED': 'Повреждено',
  'reason.CHANGED_MIND': 'Передумал(а)',
  'reason.LATE_DELIVERY': 'Привезли слишком поздно',
  'reason.OTHER': 'Другое',

  /* Wishlist */
  'wishlist.title': 'Избранное',
  'wishlist.empty': 'В избранном пусто',
  'wishlist.emptyHint': 'Нажмите на сердце у товара, чтобы сохранить его.',
  'wishlist.added': 'В избранном',
  'wishlist.removed': 'Убрано из избранного',

  /* Profile */
  'profile.title': 'Профиль',
  'profile.style': 'Стиль',
  'profile.styleHint': 'Любимые стили, цвета и бренды',
  'profile.fit': 'Размеры и посадка',
  'profile.fitHint': 'Мерки для точных рекомендаций',
  'profile.addresses': 'Адреса',
  'profile.orders': 'Мои заказы',
  'profile.returns': 'Возвраты',
  'profile.wishlist': 'Избранное',
  'profile.language': 'Язык',
  'profile.privacy': 'Данные и приватность',
  'profile.support': 'Поддержка',
  'profile.faq': 'Частые вопросы',
  'profile.about': 'О сервисе',
  'profile.terms': 'Условия',
  'profile.privacyPolicy': 'Политика конфиденциальности',
  'profile.offer': 'Публичная оферта',
  'profile.logout': 'Выйти',
  'profile.sessions': 'Активные сессии',
  'profile.phone': 'Телефон',
  'profile.phoneHint': 'Нужен курьеру для доставки',
  'profile.guest': 'Гость',

  /* Style profile */
  'style.title': 'Ваш стиль',
  'style.intro': 'Чем точнее — тем лучше подбор. Всё можно изменить потом.',
  'style.pickStyles': 'Какие стили вам близки',
  'style.pickColors': 'Любимые цвета',
  'style.avoidColors': 'Цвета, которые не носите',
  'style.budget': 'Комфортный бюджет за вещь',
  'style.fitPreference': 'Как предпочитаете носить',
  'style.favouriteBrands': 'Любимые бренды',
  'style.occasions': 'Для каких поводов ищете',
  'style.skip': 'Пропустить',
  'style.finish': 'Готово',

  /* Fit profile */
  'fit.title': 'Размеры и посадка',
  'fit.intro': 'Мерки нужны только для подбора размера. Их можно удалить в любой момент.',
  'fit.consent': 'Использовать мои мерки для подбора размера',
  'fit.consentOff': 'Персональный подбор размера выключен',
  'fit.height': 'Рост',
  'fit.weight': 'Вес',
  'fit.chest': 'Обхват груди',
  'fit.waist': 'Обхват талии',
  'fit.hips': 'Обхват бёдер',
  'fit.shoulder': 'Ширина плеч',
  'fit.inseam': 'Длина по внутр. шву',
  'fit.footLength': 'Длина стопы',
  'fit.neck': 'Обхват шеи',
  'fit.sleeve': 'Длина рукава',
  'fit.thigh': 'Обхват бедра',
  'fit.length': 'Длина изделия',
  'fit.cm': 'см',
  'fit.kg': 'кг',
  'fit.usualSizes': 'Обычный размер по брендам',
  'fit.howToMeasure': 'Как мерить',
  'fit.delete': 'Удалить мерки',
  'fit.deleteConfirm': 'Удалить все мерки? Рекомендации перестанут быть персональными.',
  'fit.preference.slim': 'Облегающе',
  'fit.preference.regular': 'Как обычно',
  'fit.preference.relaxed': 'Свободно',
  'fit.preference.oversized': 'Оверсайз',

  /* Addresses */
  'address.title': 'Адреса',
  'address.add': 'Новый адрес',
  'address.empty': 'Адресов пока нет',
  'address.label': 'Название',
  'address.labelPlaceholder': 'Дом, работа…',
  'address.recipient': 'Получатель',
  'address.phone': 'Телефон',
  'address.city': 'Город',
  'address.district': 'Район',
  'address.street': 'Улица',
  'address.building': 'Дом',
  'address.apartment': 'Квартира',
  'address.entrance': 'Подъезд',
  'address.floor': 'Этаж',
  'address.landmark': 'Ориентир',
  'address.default': 'Основной адрес',
  'address.setDefault': 'Сделать основным',
  'address.deleteConfirm': 'Удалить адрес?',

  /* Privacy */
  'privacy.title': 'Данные и приватность',
  'privacy.intro': 'Вы управляете тем, что мы о вас храним.',
  'privacy.consents': 'Согласия',
  'privacy.consent.PERSONALIZATION': 'Персональные рекомендации',
  'privacy.consent.PERSONALIZATION.hint': 'Подбор по вашей истории и стилю',
  'privacy.consent.FIT_PROFILE': 'Подбор размера по меркам',
  'privacy.consent.FIT_PROFILE.hint': 'Используем только мерки, которые вы ввели',
  'privacy.consent.MARKETING': 'Рассылки и акции',
  'privacy.consent.MARKETING.hint': 'Можно отключить в любой момент',
  'privacy.consent.ANALYTICS': 'Аналитика продукта',
  'privacy.consent.ANALYTICS.hint': 'Помогает понять, что работает плохо',
  'privacy.consent.PHOTO_ANALYSIS': 'Анализ фото',
  'privacy.consent.PHOTO_ANALYSIS.hint': 'Не используется в этой версии',
  'privacy.consent.TERMS': 'Условия использования',
  'privacy.consent.PRIVACY': 'Политика конфиденциальности',
  'privacy.export': 'Скачать мои данные',
  'privacy.exportHint': 'Машиночитаемая копия всего, что мы храним',
  'privacy.exportReady': 'Файл готов',
  'privacy.delete': 'Удалить аккаунт',
  'privacy.deleteHint': 'Заявка обрабатывается в установленный срок',
  'privacy.deleteConfirm': 'Отправить заявку на удаление аккаунта?',
  'privacy.requests': 'Мои заявки',
  'privacy.requestSent': 'Заявка отправлена',
  'privacy.personalization': 'Персонализация',
  'privacy.personalizationOff': 'Рекомендации будут обезличенными',

  /* Onboarding & consent */
  'onboarding.welcome': 'Добро пожаловать',
  'onboarding.lead': 'Бренды Ташкента, один заказ и AI-стилист, который работает только с тем, что есть в наличии.',
  'onboarding.pickLanguage': 'Выберите язык',
  'onboarding.acceptTerms': 'Я принимаю условия и политику конфиденциальности',
  'onboarding.termsRequired': 'Без согласия продолжить нельзя',
  'onboarding.start': 'Начать',
  'onboarding.setupStyle': 'Настроить стиль',
  'onboarding.later': 'Позже',

  /* Support */
  'support.title': 'Поддержка',
  'support.newTicket': 'Новое обращение',
  'support.subject': 'Тема',
  'support.message': 'Сообщение',
  'support.send': 'Отправить',
  'support.sent': 'Обращение отправлено',
  'support.noTickets': 'Обращений нет',
  'support.openInBot': 'Написать в боте',

  /* Errors */
  'err.OUT_OF_STOCK': 'Товар закончился',
  'err.RESERVATION_EXPIRED': 'Резерв истёк — обновите корзину',
  'err.QUOTE_EXPIRED': 'Расчёт устарел — пересчитываем',
  'err.CONSENT_REQUIRED': 'Нужно согласие',
  'err.RATE_LIMITED': 'Слишком много запросов — подождите немного',
  'err.NETWORK': 'Нет связи с сервером',
  'err.FEATURE_DISABLED': 'Функция пока недоступна',
  'err.UNAUTHENTICATED': 'Сессия истекла — перезапустите приложение',
};

const uz: Dict = {
  'nav.home': 'Asosiy',
  'nav.search': 'Qidiruv',
  'nav.stylist': 'Stilist',
  'nav.cart': 'Savat',
  'nav.profile': 'Profil',

  'common.back': 'Orqaga',
  'common.close': 'Yopish',
  'common.cancel': 'Bekor qilish',
  'common.save': 'Saqlash',
  'common.saved': 'Saqlandi',
  'common.apply': 'Qoʻllash',
  'common.reset': 'Tozalash',
  'common.retry': 'Qayta urinish',
  'common.continue': 'Davom etish',
  'common.done': 'Tayyor',
  'common.more': 'Yana',
  'common.less': 'Yigʻish',
  'common.all': 'Hammasi',
  'common.from': 'dan',
  'common.loading': 'Yuklanmoqda…',
  'common.error': 'Nimadir xato ketdi',
  'common.empty': 'Hozircha hech narsa yoʻq',
  'common.search': 'Qidirish',
  'common.remove': 'Oʻchirish',
  'common.edit': 'Oʻzgartirish',
  'common.add': 'Qoʻshish',
  'common.yes': 'Ha',
  'common.no': 'Yoʻq',
  'common.optional': 'majburiy emas',
  'common.required': 'majburiy',
  'common.copy': 'Nusxalash',
  'common.copied': 'Nusxalandi',
  'common.share': 'Ulashish',
  'common.days': 'kun',
  'common.pcs': 'dona',
  'common.of': 'dan',

  'home.greeting': 'Assalomu alaykum',
  'home.greetingMorning': 'Xayrli tong',
  'home.greetingEvening': 'Xayrli kech',
  'home.subtitle': 'Toshkent brendlari bir joyda',
  'home.newIn': 'Yangi',
  'home.viewAll': 'Barchasini koʻrish',
  'home.brands': 'Brendlar',
  'home.categories': 'Kategoriyalar',
  'home.looks': 'Tayyor uslublar',
  'home.sale': 'Chegirmalar',
  'home.askStylist': 'Stilistdan soʻrash',
  'home.stylistPitch': 'Tadbirni yozing — mavjud mahsulotlardan uslub yigʻamiz',
  'home.sponsored': 'Reklama',

  'search.placeholder': 'Brend, buyum yoki uslub',
  'search.filters': 'Filtrlar',
  'search.sort': 'Tartiblash',
  'search.results': 'Topildi',
  'search.nothing': 'Hech narsa topilmadi',
  'search.nothingHint': 'Filtrlarni kamaytirib yoki soʻrovni oʻzgartirib koʻring.',
  'search.didYouMean': 'Balki shuni qidirdingiz',
  'search.recent': 'Qidirgan edingiz',
  'search.popular': 'Koʻp qidiriladi',
  'search.clearFilters': 'Filtrlarni tozalash',
  'search.filtersApplied': 'filtr',
  'sort.relevance': 'Mosligi boʻyicha',
  'sort.newest': 'Avval yangisi',
  'sort.price_asc': 'Avval arzoni',
  'sort.price_desc': 'Avval qimmati',
  'sort.discount': 'Chegirma koʻproq',
  'sort.popular': 'Mashhur',
  'filter.category': 'Kategoriya',
  'filter.brand': 'Brend',
  'filter.size': 'Oʻlcham',
  'filter.color': 'Rang',
  'filter.price': 'Narx',
  'filter.material': 'Material',
  'filter.style': 'Uslub',
  'filter.season': 'Fasl',
  'filter.fitPreference': 'Oʻtirishi',
  'filter.occasion': 'Tadbir',
  'filter.inStockOnly': 'Faqat mavjud',
  'filter.discountOnly': 'Faqat chegirmali',
  'filter.priceFrom': 'Dan',
  'filter.priceTo': 'Gacha',

  'pdp.selectSize': 'Oʻlchamni tanlang',
  'pdp.size': 'Oʻlcham',
  'pdp.sizeChart': 'Oʻlcham jadvali',
  'pdp.addToCart': 'Savatga',
  'pdp.addedToCart': 'Savatga qoʻshildi',
  'pdp.outOfStock': 'Mavjud emas',
  'pdp.notifyMe': 'Kelganda xabar bering',
  'pdp.notifyMeDone': 'Kelganda xabar beramiz',
  'pdp.lastItems': 'Kam qoldi',
  'pdp.onlyLeft': '{n} dona qoldi',
  'pdp.composition': 'Tarkibi',
  'pdp.care': 'Parvarish',
  'pdp.measurements': 'Buyum oʻlchamlari',
  'pdp.delivery': 'Yetkazib berish',
  'pdp.returns': 'Qaytarish',
  'pdp.returnWindow': '{n} kun ichida qaytarish',
  'pdp.seller': 'Sotuvchi',
  'pdp.soldBy': 'Sotuvchi',
  'pdp.brand': 'Brend',
  'pdp.description': 'Tavsif',
  'pdp.details': 'Xususiyatlar',
  'pdp.countryOfOrigin': 'Ishlab chiqarilgan davlat',
  'pdp.authenticity': 'Asl mahsulot',
  'pdp.completeLook': 'Nima bilan kiyish',
  'pdp.related': 'Oʻxshash',
  'pdp.reviews': 'Izohlar',
  'pdp.noReviews': 'Hozircha izoh yoʻq',
  'pdp.verifiedPurchase': 'Xarid tasdiqlangan',
  'pdp.fitVerdict': 'Oʻtirishi haqida izohlar',
  'pdp.yourSize': 'Sizning oʻlchamingiz',
  'pdp.whySize': 'Nega bu oʻlcham',
  'pdp.improveFit': 'Oʻlchamlaringizni kiriting — aniqroq tanlaymiz',
  'pdp.fitDisclaimer': 'Bu tavsiya, oʻtirish kafolati emas.',
  'pdp.handlingDays': '{n} kunda yigʻiladi',
  'pdp.chooseSizeFirst': 'Avval oʻlchamni tanlang',
  'pdp.formality': 'Rasmiylik darajasi',
  'pdp.warmth': 'Issiqlik darajasi',

  'ai.title': 'AI-stilist',
  'ai.subtitle': 'Tadbir, budjet va kayfiyatni yozing',
  'ai.placeholder': 'Masalan: toʻyga 3 000 000 soʻmgacha uslub',
  'ai.generate': 'Uslub yigʻish',
  'ai.generating': 'Uslub yigʻilmoqda…',
  'ai.budget': 'Budjet',
  'ai.budgetAny': 'Cheklovsiz',
  'ai.total': 'Uslub jami',
  'ai.withinBudget': 'Budjet ichida',
  'ai.overBudget': 'Budjetdan yuqori',
  'ai.why': 'Nega shunday',
  'ai.swap': 'Almashtirish',
  'ai.swapItem': 'Boshqasini tanlash',
  'ai.alternatives': 'Variantlar',
  'ai.addAll': 'Butun uslubni qoʻshish',
  'ai.addedAll': 'Uslub savatda',
  'ai.sellers': 'Uslubdagi sotuvchilar: {n}',
  'ai.history': 'Sizning uslublaringiz',
  'ai.noHistory': 'Hali uslub yigʻmagansiz',
  'ai.tryAgain': 'Boshqasini yigʻish',
  'ai.refine': 'Aniqlashtirish',
  'ai.examplesTitle': 'Soʻrov namunalari',
  'ai.disclaimer': 'Uslub hozir mavjud mahsulotlardan yigʻilgan.',
  'ai.failEmptySlots': 'Bunday uslub uchun mavjud mahsulotlar yetmaydi.',
  'ai.failBudget': 'Bu budjetga uslub yigʻib boʻlmaydi.',
  'ai.failNoCombo': 'Mos kombinatsiya topilmadi.',
  'ai.failHint': 'Tadbirni oʻzgartiring, budjetni oshiring yoki rang cheklovini olib tashlang.',
  'ai.nearestBudget': 'Eng arzon oʻxshash uslub — {amount}',
  'ai.slotsFound': 'Slotlar boʻyicha topilgan mahsulotlar',
  'ai.notPersonalized': 'Uslub va oʻlchamlaringiz hisobga olinishi uchun shaxsiylashtirishni yoqing',

  'cart.title': 'Savat',
  'cart.empty': 'Savat boʻsh',
  'cart.emptyHint': 'Katalogdan mahsulot qoʻshing yoki stilist bilan uslub yigʻing.',
  'cart.goShopping': 'Katalogga',
  'cart.subtotal': 'Mahsulotlar',
  'cart.delivery': 'Yetkazib berish',
  'cart.discount': 'Chegirma',
  'cart.total': 'Jami',
  'cart.checkout': 'Buyurtma berish',
  'cart.itemCount': '{n} mahsulot',
  'cart.fromSeller': 'Sotuvchidan',
  'cart.deliverySeparately': 'Alohida yetkaziladi',
  'cart.issueOutOfStock': 'Tugadi',
  'cart.issuePriceChanged': 'Narx oʻzgardi',
  'cart.issueUnpublished': 'Sotuvdan olingan',
  'cart.issueQuantityReduced': 'Kamroq mavjud',
  'cart.fixIssues': 'Davom etish uchun pozitsiyalarni toʻgʻrilang',
  'cart.removeConfirm': 'Savatdan oʻchirilsinmi?',
  'cart.clearConfirm': 'Savat tozalansinmi?',
  'cart.promo': 'Promokod',
  'cart.promoApply': 'Qoʻllash',
  'cart.aiPick': 'Uslubdan',

  'checkout.title': 'Buyurtma',
  'checkout.address': 'Yetkazish manzili',
  'checkout.addAddress': 'Manzil qoʻshish',
  'checkout.chooseAddress': 'Manzilni tanlang',
  'checkout.deliveryMethod': 'Yetkazish usuli',
  'checkout.payment': 'Toʻlov',
  'checkout.note': 'Buyurtmaga izoh',
  'checkout.notePlaceholder': 'Masalan: yetkazishdan oldin qoʻngʻiroq qiling',
  'checkout.summary': 'Sizning buyurtmangiz',
  'checkout.pay': '{amount} toʻlash',
  'checkout.place': 'Buyurtmani tasdiqlash',
  'checkout.placing': 'Buyurtma yaratilmoqda…',
  'checkout.holdExpires': 'Mahsulot {time} gacha band qilindi',
  'checkout.holdExpired': 'Band muddati tugadi — savatni qayta hisoblaymiz',
  'checkout.quoteExpired': 'Hisob eskirdi. Yangilayapmiz.',
  'checkout.sellersNote': 'Buyurtma {n} ta pochtaga boʻlinadi — har sotuvchidan bittasi',
  'checkout.paymentsNotLive': 'Onlayn toʻlov hali ulanmagan',
  'checkout.paymentsNotLiveBody':
    'Toʻlov provayderlari alohida ulanadi. Hozir sinov toʻlovi mavjud — pul yechilmaydi, lekin buyurtma butun yoʻlni toʻliq bosib oʻtadi.',
  'checkout.sandboxPay': 'Sinov toʻlovi',
  'checkout.success': 'Buyurtma qabul qilindi',
  'checkout.successBody': 'Sotuvchi tasdiqlagach xabar yuboramiz.',
  'checkout.toOrder': 'Buyurtmaga',
  'checkout.fiscalNote': 'Chek toʻlovdan keyin keladi',

  'orders.title': 'Buyurtmalar',
  'orders.empty': 'Hozircha buyurtma yoʻq',
  'orders.active': 'Faol',
  'orders.completed': 'Yakunlangan',
  'orders.order': 'Buyurtma',
  'orders.placedAt': 'Berilgan',
  'orders.parcels': 'Pochtalar',
  'orders.parcel': 'Pochta',
  'orders.tracking': 'Kuzatish',
  'orders.trackingNumber': 'Kuzatuv raqami',
  'orders.cancel': 'Buyurtmani bekor qilish',
  'orders.cancelConfirm': 'Butun buyurtma bekor qilinsinmi?',
  'orders.cancelReason': 'Bekor qilish sababi',
  'orders.requestReturn': 'Qaytarish arizasi',
  'orders.receipt': 'Chek',
  'orders.timeline': 'Tarix',
  'orders.total': 'Buyurtma summasi',
  'orders.refunded': 'Qaytarildi',
  'orders.paymentPending': 'Toʻlov kutilmoqda',
  'orders.payNow': 'Toʻlash',
  'orders.rateFit': 'Oʻlcham qanday oʻtirdi?',
  'orders.fitRunsSmall': 'Kichik keladi',
  'orders.fitTrue': 'Oʻlchamiga mos',
  'orders.fitRunsLarge': 'Katta keladi',
  'orders.fitThanks': 'Rahmat — tavsiyalarda hisobga olamiz',

  'returns.title': 'Qaytarishlar',
  'returns.empty': 'Qaytarish yoʻq',
  'returns.create': 'Qaytarish arizasi',
  'returns.chooseItems': 'Nimani qaytaramiz',
  'returns.reason': 'Sabab',
  'returns.comment': 'Izoh',
  'returns.refundAmount': 'Qaytariladi',
  'returns.submit': 'Arizani yuborish',
  'returns.notEligible': 'Qaytarish mumkin emas',
  'returns.windowEnds': '{date} gacha qaytarish mumkin',
  'returns.handover': 'Pochtani topshirdim',
  'returns.cancel': 'Arizani bekor qilish',
  'returns.dropOff': 'Qayerga topshirish',
  'returns.created': 'Ariza yaratildi',
  'returns.createdBody': 'Sotuvchi pochtani qabul qilganda yozamiz.',
  'reason.SIZE_TOO_SMALL': 'Oʻlcham kichik',
  'reason.SIZE_TOO_LARGE': 'Oʻlcham katta',
  'reason.NOT_AS_DESCRIBED': 'Tavsifga mos emas',
  'reason.QUALITY_ISSUE': 'Sifat',
  'reason.WRONG_ITEM': 'Boshqa mahsulot keldi',
  'reason.DAMAGED': 'Shikastlangan',
  'reason.CHANGED_MIND': 'Fikrim oʻzgardi',
  'reason.LATE_DELIVERY': 'Juda kech keltirildi',
  'reason.OTHER': 'Boshqa',

  'wishlist.title': 'Saralangan',
  'wishlist.empty': 'Saralangan boʻsh',
  'wishlist.emptyHint': 'Saqlash uchun mahsulotdagi yurakni bosing.',
  'wishlist.added': 'Saralanganda',
  'wishlist.removed': 'Saralangandan olindi',

  'profile.title': 'Profil',
  'profile.style': 'Uslub',
  'profile.styleHint': 'Yoqtirgan uslublar, ranglar va brendlar',
  'profile.fit': 'Oʻlchamlar',
  'profile.fitHint': 'Aniq tavsiyalar uchun oʻlchamlar',
  'profile.addresses': 'Manzillar',
  'profile.orders': 'Buyurtmalarim',
  'profile.returns': 'Qaytarishlar',
  'profile.wishlist': 'Saralangan',
  'profile.language': 'Til',
  'profile.privacy': 'Maʼlumotlar va maxfiylik',
  'profile.support': 'Yordam',
  'profile.faq': 'Koʻp beriladigan savollar',
  'profile.about': 'Servis haqida',
  'profile.terms': 'Shartlar',
  'profile.privacyPolicy': 'Maxfiylik siyosati',
  'profile.offer': 'Ommaviy oferta',
  'profile.logout': 'Chiqish',
  'profile.sessions': 'Faol seanslar',
  'profile.phone': 'Telefon',
  'profile.phoneHint': 'Yetkazib beruvchiga kerak',
  'profile.guest': 'Mehmon',

  'style.title': 'Sizning uslubingiz',
  'style.intro': 'Qanchalik aniq boʻlsa, tanlov shunchalik yaxshi. Keyin oʻzgartirish mumkin.',
  'style.pickStyles': 'Qaysi uslublar sizga yaqin',
  'style.pickColors': 'Yoqtirgan ranglar',
  'style.avoidColors': 'Kiymaydigan ranglar',
  'style.budget': 'Bitta buyum uchun qulay budjet',
  'style.fitPreference': 'Qanday kiyishni afzal koʻrasiz',
  'style.favouriteBrands': 'Yoqtirgan brendlar',
  'style.occasions': 'Qanday tadbirlar uchun',
  'style.skip': 'Oʻtkazib yuborish',
  'style.finish': 'Tayyor',

  'fit.title': 'Oʻlchamlar va oʻtirishi',
  'fit.intro': 'Oʻlchamlar faqat oʻlcham tanlash uchun. Istalgan vaqtda oʻchirish mumkin.',
  'fit.consent': 'Oʻlcham tanlash uchun oʻlchamlarimdan foydalanish',
  'fit.consentOff': 'Shaxsiy oʻlcham tanlash oʻchirilgan',
  'fit.height': 'Boʻy',
  'fit.weight': 'Vazn',
  'fit.chest': 'Koʻkrak aylanasi',
  'fit.waist': 'Bel aylanasi',
  'fit.hips': 'Son aylanasi',
  'fit.shoulder': 'Yelka kengligi',
  'fit.inseam': 'Ichki chok uzunligi',
  'fit.footLength': 'Oyoq uzunligi',
  'fit.neck': 'Boʻyin aylanasi',
  'fit.sleeve': 'Yeng uzunligi',
  'fit.thigh': 'Son aylanasi',
  'fit.length': 'Buyum uzunligi',
  'fit.cm': 'sm',
  'fit.kg': 'kg',
  'fit.usualSizes': 'Brendlar boʻyicha odatdagi oʻlcham',
  'fit.howToMeasure': 'Qanday oʻlchash',
  'fit.delete': 'Oʻlchamlarni oʻchirish',
  'fit.deleteConfirm': 'Barcha oʻlchamlar oʻchirilsinmi? Tavsiyalar shaxsiy boʻlmaydi.',
  'fit.preference.slim': 'Tanaga yaqin',
  'fit.preference.regular': 'Odatdagidek',
  'fit.preference.relaxed': 'Erkin',
  'fit.preference.oversized': 'Oversayz',

  'address.title': 'Manzillar',
  'address.add': 'Yangi manzil',
  'address.empty': 'Hozircha manzil yoʻq',
  'address.label': 'Nomi',
  'address.labelPlaceholder': 'Uy, ish…',
  'address.recipient': 'Qabul qiluvchi',
  'address.phone': 'Telefon',
  'address.city': 'Shahar',
  'address.district': 'Tuman',
  'address.street': 'Koʻcha',
  'address.building': 'Uy',
  'address.apartment': 'Xonadon',
  'address.entrance': 'Podyezd',
  'address.floor': 'Qavat',
  'address.landmark': 'Moʻljal',
  'address.default': 'Asosiy manzil',
  'address.setDefault': 'Asosiy qilish',
  'address.deleteConfirm': 'Manzil oʻchirilsinmi?',

  'privacy.title': 'Maʼlumotlar va maxfiylik',
  'privacy.intro': 'Biz nimani saqlashimizni siz boshqarasiz.',
  'privacy.consents': 'Roziliklar',
  'privacy.consent.PERSONALIZATION': 'Shaxsiy tavsiyalar',
  'privacy.consent.PERSONALIZATION.hint': 'Tarix va uslubingiz boʻyicha tanlov',
  'privacy.consent.FIT_PROFILE': 'Oʻlchamlar boʻyicha tanlov',
  'privacy.consent.FIT_PROFILE.hint': 'Faqat siz kiritgan oʻlchamlardan foydalanamiz',
  'privacy.consent.MARKETING': 'Xabarnomalar va aksiyalar',
  'privacy.consent.MARKETING.hint': 'Istalgan vaqtda oʻchirish mumkin',
  'privacy.consent.ANALYTICS': 'Mahsulot tahlili',
  'privacy.consent.ANALYTICS.hint': 'Nima yomon ishlayotganini tushunishga yordam beradi',
  'privacy.consent.PHOTO_ANALYSIS': 'Foto tahlili',
  'privacy.consent.PHOTO_ANALYSIS.hint': 'Bu versiyada ishlatilmaydi',
  'privacy.consent.TERMS': 'Foydalanish shartlari',
  'privacy.consent.PRIVACY': 'Maxfiylik siyosati',
  'privacy.export': 'Maʼlumotlarimni yuklab olish',
  'privacy.exportHint': 'Saqlanayotgan hamma narsaning mashina oʻqiydigan nusxasi',
  'privacy.exportReady': 'Fayl tayyor',
  'privacy.delete': 'Hisobni oʻchirish',
  'privacy.deleteHint': 'Ariza belgilangan muddatda koʻrib chiqiladi',
  'privacy.deleteConfirm': 'Hisobni oʻchirish arizasi yuborilsinmi?',
  'privacy.requests': 'Mening arizalarim',
  'privacy.requestSent': 'Ariza yuborildi',
  'privacy.personalization': 'Shaxsiylashtirish',
  'privacy.personalizationOff': 'Tavsiyalar shaxsiy boʻlmaydi',

  'onboarding.welcome': 'Xush kelibsiz',
  'onboarding.lead':
    'Toshkent brendlari, bitta buyurtma va faqat mavjud mahsulotlar bilan ishlaydigan AI-stilist.',
  'onboarding.pickLanguage': 'Tilni tanlang',
  'onboarding.acceptTerms': 'Shartlar va maxfiylik siyosatini qabul qilaman',
  'onboarding.termsRequired': 'Rozilik boʻlmasa davom etib boʻlmaydi',
  'onboarding.start': 'Boshlash',
  'onboarding.setupStyle': 'Uslubni sozlash',
  'onboarding.later': 'Keyinroq',

  'support.title': 'Yordam',
  'support.newTicket': 'Yangi murojaat',
  'support.subject': 'Mavzu',
  'support.message': 'Xabar',
  'support.send': 'Yuborish',
  'support.sent': 'Murojaat yuborildi',
  'support.noTickets': 'Murojaat yoʻq',
  'support.openInBot': 'Botda yozish',

  'err.OUT_OF_STOCK': 'Mahsulot tugadi',
  'err.RESERVATION_EXPIRED': 'Band muddati tugadi — savatni yangilang',
  'err.QUOTE_EXPIRED': 'Hisob eskirdi — qayta hisoblayapmiz',
  'err.CONSENT_REQUIRED': 'Rozilik kerak',
  'err.RATE_LIMITED': 'Soʻrov juda koʻp — bir oz kuting',
  'err.NETWORK': 'Server bilan aloqa yoʻq',
  'err.FEATURE_DISABLED': 'Funksiya hozircha mavjud emas',
  'err.UNAUTHENTICATED': 'Seans tugadi — ilovani qayta ishga tushiring',
};

const en: Dict = {
  'nav.home': 'Home',
  'nav.search': 'Search',
  'nav.stylist': 'Stylist',
  'nav.cart': 'Cart',
  'nav.profile': 'Profile',

  'common.back': 'Back',
  'common.close': 'Close',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.saved': 'Saved',
  'common.apply': 'Apply',
  'common.reset': 'Reset',
  'common.retry': 'Try again',
  'common.continue': 'Continue',
  'common.done': 'Done',
  'common.more': 'More',
  'common.less': 'Less',
  'common.all': 'All',
  'common.from': 'from',
  'common.loading': 'Loading…',
  'common.error': 'Something went wrong',
  'common.empty': 'Nothing here yet',
  'common.search': 'Search',
  'common.remove': 'Remove',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.optional': 'optional',
  'common.required': 'required',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.share': 'Share',
  'common.days': 'days',
  'common.pcs': 'pcs',
  'common.of': 'of',

  'home.greeting': 'Good afternoon',
  'home.greetingMorning': 'Good morning',
  'home.greetingEvening': 'Good evening',
  'home.subtitle': 'Tashkent brands in one place',
  'home.newIn': 'New in',
  'home.viewAll': 'View all',
  'home.brands': 'Brands',
  'home.categories': 'Categories',
  'home.looks': 'Ready-made looks',
  'home.sale': 'Sale',
  'home.askStylist': 'Ask the stylist',
  'home.stylistPitch': 'Describe the occasion — we build a look from what is actually in stock',
  'home.sponsored': 'Sponsored',

  'search.placeholder': 'Brand, item or look',
  'search.filters': 'Filters',
  'search.sort': 'Sort',
  'search.results': 'Found',
  'search.nothing': 'Nothing found',
  'search.nothingHint': 'Try removing a filter or changing the query.',
  'search.didYouMean': 'Did you mean',
  'search.recent': 'You searched',
  'search.popular': 'Popular searches',
  'search.clearFilters': 'Clear filters',
  'search.filtersApplied': 'filter(s)',
  'sort.relevance': 'Most relevant',
  'sort.newest': 'Newest first',
  'sort.price_asc': 'Price: low to high',
  'sort.price_desc': 'Price: high to low',
  'sort.discount': 'Biggest discount',
  'sort.popular': 'Popular',
  'filter.category': 'Category',
  'filter.brand': 'Brand',
  'filter.size': 'Size',
  'filter.color': 'Colour',
  'filter.price': 'Price',
  'filter.material': 'Material',
  'filter.style': 'Style',
  'filter.season': 'Season',
  'filter.fitPreference': 'Fit',
  'filter.occasion': 'Occasion',
  'filter.inStockOnly': 'In stock only',
  'filter.discountOnly': 'On sale only',
  'filter.priceFrom': 'From',
  'filter.priceTo': 'To',

  'pdp.selectSize': 'Select a size',
  'pdp.size': 'Size',
  'pdp.sizeChart': 'Size chart',
  'pdp.addToCart': 'Add to cart',
  'pdp.addedToCart': 'Added to cart',
  'pdp.outOfStock': 'Out of stock',
  'pdp.notifyMe': 'Notify me when it is back',
  'pdp.notifyMeDone': 'We will let you know',
  'pdp.lastItems': 'Low stock',
  'pdp.onlyLeft': 'Only {n} left',
  'pdp.composition': 'Composition',
  'pdp.care': 'Care',
  'pdp.measurements': 'Garment measurements',
  'pdp.delivery': 'Delivery',
  'pdp.returns': 'Returns',
  'pdp.returnWindow': 'Returns within {n} days',
  'pdp.seller': 'Seller',
  'pdp.soldBy': 'Sold by',
  'pdp.brand': 'Brand',
  'pdp.description': 'Description',
  'pdp.details': 'Details',
  'pdp.countryOfOrigin': 'Country of origin',
  'pdp.authenticity': 'Authenticity',
  'pdp.completeLook': 'Complete the look',
  'pdp.related': 'You may also like',
  'pdp.reviews': 'Reviews',
  'pdp.noReviews': 'No reviews yet',
  'pdp.verifiedPurchase': 'Verified purchase',
  'pdp.fitVerdict': 'What shoppers say about the fit',
  'pdp.yourSize': 'Your size',
  'pdp.whySize': 'Why this size',
  'pdp.improveFit': 'Add your measurements for a sharper answer',
  'pdp.fitDisclaimer': 'This is a recommendation, not a guarantee of fit.',
  'pdp.handlingDays': 'Dispatched in {n} days',
  'pdp.chooseSizeFirst': 'Pick a size first',
  'pdp.formality': 'Formality',
  'pdp.warmth': 'Insulation',

  'ai.title': 'AI stylist',
  'ai.subtitle': 'Describe the occasion, budget and mood',
  'ai.placeholder': 'For example: a wedding look under 3 000 000 soum',
  'ai.generate': 'Build a look',
  'ai.generating': 'Building the look…',
  'ai.budget': 'Budget',
  'ai.budgetAny': 'No limit',
  'ai.total': 'Look total',
  'ai.withinBudget': 'Within budget',
  'ai.overBudget': 'Over budget',
  'ai.why': 'Why this works',
  'ai.swap': 'Swap',
  'ai.swapItem': 'Choose another',
  'ai.alternatives': 'Alternatives',
  'ai.addAll': 'Add the whole look',
  'ai.addedAll': 'Look is in the cart',
  'ai.sellers': 'Sellers in this look: {n}',
  'ai.history': 'Your looks',
  'ai.noHistory': 'You have not built a look yet',
  'ai.tryAgain': 'Build another',
  'ai.refine': 'Refine',
  'ai.examplesTitle': 'Example briefs',
  'ai.disclaimer': 'Built only from items that are in stock right now.',
  'ai.failEmptySlots': 'There is not enough in stock for a look like this.',
  'ai.failBudget': 'A look cannot be built within this budget.',
  'ai.failNoCombo': 'No compatible combination was found.',
  'ai.failHint': 'Try a different occasion, a higher budget, or drop the colour constraint.',
  'ai.nearestBudget': 'The most affordable similar look is {amount}',
  'ai.slotsFound': 'Items found per slot',
  'ai.notPersonalized': 'Turn on personalisation so your style and sizes are taken into account',

  'cart.title': 'Cart',
  'cart.empty': 'Your cart is empty',
  'cart.emptyHint': 'Add something from the catalogue, or build a look with the stylist.',
  'cart.goShopping': 'Browse the catalogue',
  'cart.subtotal': 'Items',
  'cart.delivery': 'Delivery',
  'cart.discount': 'Discount',
  'cart.total': 'Total',
  'cart.checkout': 'Checkout',
  'cart.itemCount': '{n} item(s)',
  'cart.fromSeller': 'From',
  'cart.deliverySeparately': 'Ships separately',
  'cart.issueOutOfStock': 'Sold out',
  'cart.issuePriceChanged': 'Price changed',
  'cart.issueUnpublished': 'No longer for sale',
  'cart.issueQuantityReduced': 'Fewer available',
  'cart.fixIssues': 'Fix the flagged lines to continue',
  'cart.removeConfirm': 'Remove from the cart?',
  'cart.clearConfirm': 'Empty the cart?',
  'cart.promo': 'Promo code',
  'cart.promoApply': 'Apply',
  'cart.aiPick': 'From a look',

  'checkout.title': 'Checkout',
  'checkout.address': 'Delivery address',
  'checkout.addAddress': 'Add an address',
  'checkout.chooseAddress': 'Choose an address',
  'checkout.deliveryMethod': 'Delivery method',
  'checkout.payment': 'Payment',
  'checkout.note': 'Order note',
  'checkout.notePlaceholder': 'For example: call before delivery',
  'checkout.summary': 'Your order',
  'checkout.pay': 'Pay {amount}',
  'checkout.place': 'Place the order',
  'checkout.placing': 'Creating the order…',
  'checkout.holdExpires': 'Items held until {time}',
  'checkout.holdExpired': 'The hold lapsed — recalculating your cart',
  'checkout.quoteExpired': 'The quote is stale. Refreshing.',
  'checkout.sellersNote': 'This order splits into {n} parcel(s) — one per seller',
  'checkout.paymentsNotLive': 'Online payment is not connected yet',
  'checkout.paymentsNotLiveBody':
    'Payment providers are connected separately. A sandbox payment is available now — no money moves, but the order runs through the whole flow.',
  'checkout.sandboxPay': 'Sandbox payment',
  'checkout.success': 'Order placed',
  'checkout.successBody': 'We will notify you as soon as the seller confirms.',
  'checkout.toOrder': 'View the order',
  'checkout.fiscalNote': 'The receipt follows the payment',

  'orders.title': 'Orders',
  'orders.empty': 'No orders yet',
  'orders.active': 'Active',
  'orders.completed': 'Completed',
  'orders.order': 'Order',
  'orders.placedAt': 'Placed',
  'orders.parcels': 'Parcels',
  'orders.parcel': 'Parcel',
  'orders.tracking': 'Tracking',
  'orders.trackingNumber': 'Tracking number',
  'orders.cancel': 'Cancel the order',
  'orders.cancelConfirm': 'Cancel the whole order?',
  'orders.cancelReason': 'Reason',
  'orders.requestReturn': 'Request a return',
  'orders.receipt': 'Receipt',
  'orders.timeline': 'History',
  'orders.total': 'Order total',
  'orders.refunded': 'Refunded',
  'orders.paymentPending': 'Awaiting payment',
  'orders.payNow': 'Pay now',
  'orders.rateFit': 'How did the size fit?',
  'orders.fitRunsSmall': 'Runs small',
  'orders.fitTrue': 'True to size',
  'orders.fitRunsLarge': 'Runs large',
  'orders.fitThanks': 'Thank you — it will shape our recommendations',

  'returns.title': 'Returns',
  'returns.empty': 'No returns',
  'returns.create': 'Request a return',
  'returns.chooseItems': 'What are you returning',
  'returns.reason': 'Reason',
  'returns.comment': 'Comment',
  'returns.refundAmount': 'Refund',
  'returns.submit': 'Submit the request',
  'returns.notEligible': 'Returns are not available',
  'returns.windowEnds': 'Returnable until {date}',
  'returns.handover': 'I have handed the parcel over',
  'returns.cancel': 'Cancel the request',
  'returns.dropOff': 'Where to hand it over',
  'returns.created': 'Request created',
  'returns.createdBody': 'We will write when the seller receives the parcel.',
  'reason.SIZE_TOO_SMALL': 'Too small',
  'reason.SIZE_TOO_LARGE': 'Too large',
  'reason.NOT_AS_DESCRIBED': 'Not as described',
  'reason.QUALITY_ISSUE': 'Quality issue',
  'reason.WRONG_ITEM': 'Wrong item sent',
  'reason.DAMAGED': 'Damaged',
  'reason.CHANGED_MIND': 'Changed my mind',
  'reason.LATE_DELIVERY': 'Arrived too late',
  'reason.OTHER': 'Other',

  'wishlist.title': 'Saved',
  'wishlist.empty': 'Nothing saved yet',
  'wishlist.emptyHint': 'Tap the heart on a product to keep it here.',
  'wishlist.added': 'Saved',
  'wishlist.removed': 'Removed',

  'profile.title': 'Profile',
  'profile.style': 'Style',
  'profile.styleHint': 'Favourite styles, colours and brands',
  'profile.fit': 'Sizes and fit',
  'profile.fitHint': 'Measurements for sharper recommendations',
  'profile.addresses': 'Addresses',
  'profile.orders': 'My orders',
  'profile.returns': 'Returns',
  'profile.wishlist': 'Saved',
  'profile.language': 'Language',
  'profile.privacy': 'Data and privacy',
  'profile.support': 'Support',
  'profile.faq': 'FAQ',
  'profile.about': 'About',
  'profile.terms': 'Terms',
  'profile.privacyPolicy': 'Privacy policy',
  'profile.offer': 'Public offer',
  'profile.logout': 'Sign out',
  'profile.sessions': 'Active sessions',
  'profile.phone': 'Phone',
  'profile.phoneHint': 'The courier needs it for delivery',
  'profile.guest': 'Guest',

  'style.title': 'Your style',
  'style.intro': 'The more precise, the better the picks. All of it can be changed later.',
  'style.pickStyles': 'Which styles feel like you',
  'style.pickColors': 'Colours you like',
  'style.avoidColors': 'Colours you never wear',
  'style.budget': 'Comfortable budget per item',
  'style.fitPreference': 'How you like things to sit',
  'style.favouriteBrands': 'Favourite brands',
  'style.occasions': 'What you are shopping for',
  'style.skip': 'Skip',
  'style.finish': 'Done',

  'fit.title': 'Sizes and fit',
  'fit.intro': 'Measurements are used only to pick a size. You can delete them at any time.',
  'fit.consent': 'Use my measurements to recommend a size',
  'fit.consentOff': 'Personalised sizing is off',
  'fit.height': 'Height',
  'fit.weight': 'Weight',
  'fit.chest': 'Chest',
  'fit.waist': 'Waist',
  'fit.hips': 'Hips',
  'fit.shoulder': 'Shoulder width',
  'fit.inseam': 'Inseam',
  'fit.footLength': 'Foot length',
  'fit.neck': 'Neck',
  'fit.sleeve': 'Sleeve length',
  'fit.thigh': 'Thigh',
  'fit.length': 'Garment length',
  'fit.cm': 'cm',
  'fit.kg': 'kg',
  'fit.usualSizes': 'Your usual size per brand',
  'fit.howToMeasure': 'How to measure',
  'fit.delete': 'Delete my measurements',
  'fit.deleteConfirm': 'Delete all measurements? Recommendations will stop being personal.',
  'fit.preference.slim': 'Close to the body',
  'fit.preference.regular': 'As usual',
  'fit.preference.relaxed': 'Relaxed',
  'fit.preference.oversized': 'Oversized',

  'address.title': 'Addresses',
  'address.add': 'New address',
  'address.empty': 'No addresses yet',
  'address.label': 'Label',
  'address.labelPlaceholder': 'Home, work…',
  'address.recipient': 'Recipient',
  'address.phone': 'Phone',
  'address.city': 'City',
  'address.district': 'District',
  'address.street': 'Street',
  'address.building': 'Building',
  'address.apartment': 'Apartment',
  'address.entrance': 'Entrance',
  'address.floor': 'Floor',
  'address.landmark': 'Landmark',
  'address.default': 'Default address',
  'address.setDefault': 'Make default',
  'address.deleteConfirm': 'Delete this address?',

  'privacy.title': 'Data and privacy',
  'privacy.intro': 'You decide what we keep about you.',
  'privacy.consents': 'Consents',
  'privacy.consent.PERSONALIZATION': 'Personal recommendations',
  'privacy.consent.PERSONALIZATION.hint': 'Picks based on your history and style',
  'privacy.consent.FIT_PROFILE': 'Size recommendations from measurements',
  'privacy.consent.FIT_PROFILE.hint': 'Only the measurements you entered are used',
  'privacy.consent.MARKETING': 'Promotions and newsletters',
  'privacy.consent.MARKETING.hint': 'Can be turned off at any time',
  'privacy.consent.ANALYTICS': 'Product analytics',
  'privacy.consent.ANALYTICS.hint': 'Helps us see what works badly',
  'privacy.consent.PHOTO_ANALYSIS': 'Photo analysis',
  'privacy.consent.PHOTO_ANALYSIS.hint': 'Not used in this release',
  'privacy.consent.TERMS': 'Terms of use',
  'privacy.consent.PRIVACY': 'Privacy policy',
  'privacy.export': 'Download my data',
  'privacy.exportHint': 'A machine-readable copy of everything we hold',
  'privacy.exportReady': 'Your file is ready',
  'privacy.delete': 'Delete my account',
  'privacy.deleteHint': 'The request is processed within the statutory period',
  'privacy.deleteConfirm': 'Send an account deletion request?',
  'privacy.requests': 'My requests',
  'privacy.requestSent': 'Request sent',
  'privacy.personalization': 'Personalisation',
  'privacy.personalizationOff': 'Recommendations will not be personal',

  'onboarding.welcome': 'Welcome',
  'onboarding.lead':
    'Tashkent brands, one order, and an AI stylist that only works with what is actually in stock.',
  'onboarding.pickLanguage': 'Choose a language',
  'onboarding.acceptTerms': 'I accept the terms and the privacy policy',
  'onboarding.termsRequired': 'We cannot continue without your consent',
  'onboarding.start': 'Get started',
  'onboarding.setupStyle': 'Set up my style',
  'onboarding.later': 'Later',

  'support.title': 'Support',
  'support.newTicket': 'New request',
  'support.subject': 'Subject',
  'support.message': 'Message',
  'support.send': 'Send',
  'support.sent': 'Request sent',
  'support.noTickets': 'No requests',
  'support.openInBot': 'Message us in the bot',

  'err.OUT_OF_STOCK': 'This item sold out',
  'err.RESERVATION_EXPIRED': 'The hold lapsed — refresh your cart',
  'err.QUOTE_EXPIRED': 'The quote is stale — recalculating',
  'err.CONSENT_REQUIRED': 'Your consent is needed',
  'err.RATE_LIMITED': 'Too many requests — give it a moment',
  'err.NETWORK': 'No connection to the server',
  'err.FEATURE_DISABLED': 'Not available yet',
  'err.UNAUTHENTICATED': 'Your session expired — reopen the app',
};

const DICTS: Record<Locale, Dict> = { ru, uz, en };

/**
 * Screen copy first, then the shared catalogue, then the key itself. Returning
 * the key rather than an empty string makes a missing translation obvious in
 * review instead of silently blanking a button.
 */
export function t(locale: Locale, key: string, params?: Record<string, string | number>): string {
  const own = DICTS[locale]?.[key] ?? DICTS.ru[key];
  const template = own ?? translateCore(locale, key, params);
  if (!own) return template;
  return interpolate(template, params);
}

function interpolate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (match, name: string) =>
    name in params ? String(params[name]) : match,
  );
}

/** ADM-011: which keys a locale is still missing, so the gap is measurable. */
export function missingKeys(locale: Locale): string[] {
  const reference = Object.keys(ru);
  const target = DICTS[locale] ?? {};
  return reference.filter((key) => !(key in target));
}

export { LOCALES };
export type { Locale };
